name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[^#].{74}'
          error: 'The maximum line length of 74 characters is exceeded.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true'       # optional: this excludes the title of a pull request
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.+(fix|feature|enhancement): \#[0-9]+ .*$'
          error: 'You need at least one "fix|feature|enhancement: #<issue number>" line.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true'       # optional: this excludes the title of a pull request
